const products = [
  {
    id: 1,
    name: "Mango",
    desc: "Sweet and juicy",
    price: "250",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "https://fruit-backend-d30x.onrender.com/image/mango.jfif",
    qty: 1,
  },
  {
    id: 2,
    name: "Orange",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/orange.jfif",
    qty: 1,
  },
  {
    id: 3,
    name: "Pomegranate",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/pomegranate.jfif",
    qty: 1,
  },
  {
    id: 4,
    name: "Strawberry",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/straw.jfif",
    qty: 1,
  },
  {
    id: 5,
    name: "Apple",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/apple.jfif",
    qty: 1,
  },
  {
    id: 6,
    name: "Cherry",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/cherry.jfif",
    qty: 1,
  },
  {
    id: 7,
    name: "Grapes",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/grape.jfif",
    qty: 1,
  },
  {
    id: 8,
    name: "Guava",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/guava.jfif",
    qty: 1,
  },
  {
    id: 9,
    name: "Banana",
    desc: "Sweet and juicy",
    price: "50",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/banana.jfif",
    qty: 1,
  },
  {
    id: 10,
    name: "Papaya",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/papaya.jfif",
    qty: 1,
  },
  {
    id: 11,
    name: "Watermelon",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/melon.jfif",
    qty: 1,
  },
  {
    id: 12,
    name: "Pineapple",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/pine.jfif",
    qty: 1,
  },
  {
    id: 13,
    name: "Pear",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/pear.jfif",
    qty: 1,
  },
  {
    id: 14,
    name: "Peach",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/peach.jfif",
    qty: 1,
  },
  {
    id: 15,
    name: "Kiwi",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/kiwi.jfif",
    qty: 1,
  },
  {
    id: 16,
    name: "Coconut",
    desc: "Sweet and juicy",
    price: "60",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/coco.jfif",
    qty: 1,
  },
  {
    id: 17,
    name: "Litchi",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/litchi.jfif",
    qty: 1,
  },
  {
    id: 18,
    name: "Muskmelon",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/musk.jfif",
    qty: 1,
  },
  {
    id: 19,
    name: "Fig",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/fig.jfif",
    qty: 1,
  },
  {
    id: 20,
    name: "Plum",
    desc: "Sweet and juicy",
    price: "210",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/plum.jfif",
    qty: 1,
  },
  {
    id: 21,
    name: "Lemon",
    desc: "Sweet and juicy",
    price: "10",
    rating: "5",
    review: "sweetest fruit",
    category: "Fruit",
    image: "/image/lemon.jfif",
    qty: 1,
  },
];
module.exports = products;
